# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: pack package
        run: choco pack .\src\ProtonVPN.nuspec
      - name: Test Chocopackage
        run: choco install protonvpn --debug --verbose --force --pre --source ".;https://community.chocolatey.org/api/v2/"
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    needs: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: pack package
        run: choco pack .\src\ProtonVPN.nuspec
      # Runs a single command using the runners shell
      - name: Push to Choco
        run: choco push .\src\ProtonVPN.nuspec --source https://push.chocolatey.org/ --api-key ${{ secrets.API_Key }}
